server:
  port: 9001

spring :
  application:
    name: product-service
  datasource:
    url: "jdbc:mysql://localhost:3306/db_tasc_product"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 22102003
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 100MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true