server:
  port: 9003
spring:
  application:
    name : payment-service
  datasource:
    url: "jdbc:mysql://localhost:3306/db_tasc_payment"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 22102003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true